services:
  talkvera-iframe:
    build: .
    container_name: talkvera-iframe
    labels:
      traefik.enable: "true"

      # root domain (menggunakan variabel dari .env)
      traefik.http.routers.talkvera-iframe.entrypoints: websecure
      traefik.http.routers.talkvera-iframe.rule: Host(`chat.${ROOT_DOMAIN}`)
      traefik.http.routers.talkvera-iframe.service: talkvera-iframe-service
      traefik.http.routers.talkvera-iframe.tls.certresolver: mytlschallenge

      traefik.http.services.talkvera-iframe-service.loadbalancer.server.port: "80"
    expose:
      - "80"
    restart: always
    networks:
      - default
networks:
  default:
    external: true
    name: root_default